services:
  filestash:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: filestash:local
    restart: always
    environment:
    # - FILESTASH_PATH
    # - FILESTASH_PORT
    # - FILESTASH_BASE
    # - APPLICATION_URL
      ADMIN_PASSWORD: "$$2a$$12$$G2pO8NghkdJ8x8E8eV.IgeygXPR9UlXVP5Pw3mu1gtumJEafJWqsO"
    # - CONFIG_SECRET
    # - CONFIG_ENCRYPT
    # - LOG_LEVEL
    # - DEBUG
    ports:
    - "8334:8334"
    volumes:
    - filestash:/app/data/state/

volumes:
    filestash: {}
